### ISSUE TITLE
Is there a way to not display the status of deleted comments?

### ISSUE THREAD

**Issue by btayalew** [jacobwb/hashover-next#242]
After I deleted some comments in the database their status is still displayed in the thread. Is there a way to stop displaying the status of deleted comments?

**Comment by jacobwb** [comment]
Sorry for the long delay.

Unfortunately, there is not. You can hide them using CSS, though...

With something like this:

```css
.hashover .hashover-deleted {
    display: none;
}
```

If the comment had replies, they will be hidden as well.

This code will hide deleted comments that don't have replies:

```css
.hashover .hashover-deleted:not(.hashover-has-replies) {
    display: none;
}
```

I hope this helps.
